# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = '2'

# Custom docker host VM
Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = 'trusty'
  config.vm.box_url = 'http://cloud-images.ubuntu.com/vagrant/trusty/current/trusty-server-cloudimg-amd64-vagrant-disk1.box'

  # forwarding port for docker container
  config.vm.network :forwarded_port, guest: 80, host: 8000
  config.vm.provision 'docker'

  # ensure that the vagrant user belongs to the docker group
  config.vm.provision :shell, inline: "usermod -a -G docker vagrant; "

  # kill all open ssh connections, forcing vagrant to relogin
  config.vm.provision :shell, inline: "ps aux | grep 'sshd:' | awk '{print $2}' | xargs kill"
end
